<?php

// This is a autogenerated file:Grupo

class Grupo {
    private string $grupo; // json:grupo Required

    /**
     * @param string $grupo
     */
    public function __construct(string $grupo) {
        $this->grupo = $grupo;
    }

    /**
     * @param string $value
     * @throws Exception
     * @return string
     */
    public static function fromGrupo(string $value): string {
        return $value; /*string*/
    }

    /**
     * @throws Exception
     * @return string
     */
    public function toGrupo(): string {
        if (Grupo::validateGrupo($this->grupo))  {
            return $this->grupo; /*string*/
        }
        throw new Exception('never get to this Grupo::grupo');
    }

    /**
     * @param string
     * @return bool
     * @throws Exception
     */
    public static function validateGrupo(string $value): bool {
        if (!is_string($value)) {
            throw new Exception("Attribute Error:Grupo::grupo");
        }
        return true;
    }

    /**
     * @return string
     */
    public function getGrupo(): string {
        return $this->grupo;
    }

    /**
     * @param string
     * @throws Exception
     */
    public function setGrupo(string $value) {
        if (Grupo::validateGrupo($value))  {
            $this->grupo = $value;
        }
    }

    /**
     * @return string
     */
    public static function sampleGrupo(): string {
        return 'Grupo::grupo::31'; /*31:grupo*/
    }

    /**
     * @throws Exception
     * @return bool
     */
    public function validate(): bool {
        return Grupo::validateGrupo($this->grupo);
    }

    /**
     * @return stdClass
     * @throws Exception
     */
    public function to(): stdClass  {
        $out = new stdClass();
        $out->{'grupo'} = $this->toGrupo();
        return $out;
    }

    /**
     * @param stdClass $obj
     * @return Grupo
     * @throws Exception
     */
    public function from(stdClass $obj): Grupo {
        Grupo::validateGrupo($this->grupo, true);
        return new Grupo(
         Grupo::fromGrupo($obj->{'grupo'})
        );
    }

    /**
     * @return Grupo
     */
    public static function sample(): Grupo {
        return new Grupo(
         Grupo::sampleGrupo()
        );
    }
}
?>
